2016/07/13 18:15:27 [notice] 9563#0: signal process started
2016/07/13 18:15:27 [error] 9563#0: open() "/opt/openresty--with-luajit--without-http_redis2_module--with-http_iconv_module/nginx/logs/nginx.pid" failed (2: No such file or directory)
2016/08/04 23:31:18 [emerg] 15317#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/08/04 23:31:18 [emerg] 15317#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/08/04 23:31:18 [emerg] 15317#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/08/04 23:31:18 [emerg] 15317#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/08/04 23:31:18 [emerg] 15317#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/08/04 23:31:18 [emerg] 15317#0: still could not bind()
2016/08/04 23:36:47 [notice] 15359#0: signal process started
2016/08/05 03:22:45 [error] 15360#0: *6 open() "/opt/openresty/nginx/html/muieblackcat" failed (2: No such file or directory), client: 149.56.96.31, server: localhost, request: "GET /muieblackcat HTTP/1.1", host: "119.29.33.243"
2016/08/05 03:22:46 [error] 15360#0: *7 open() "/opt/openresty/nginx/html/phpMyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 149.56.96.31, server: localhost, request: "GET //phpMyAdmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 03:22:46 [error] 15360#0: *8 open() "/opt/openresty/nginx/html/phpmyadmin/scripts/setup.php" failed (2: No such file or directory), client: 149.56.96.31, server: localhost, request: "GET //phpmyadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 03:22:47 [error] 15360#0: *9 open() "/opt/openresty/nginx/html/pma/scripts/setup.php" failed (2: No such file or directory), client: 149.56.96.31, server: localhost, request: "GET //pma/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 03:22:47 [error] 15360#0: *10 open() "/opt/openresty/nginx/html/myadmin/scripts/setup.php" failed (2: No such file or directory), client: 149.56.96.31, server: localhost, request: "GET //myadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 03:22:48 [error] 15360#0: *11 open() "/opt/openresty/nginx/html/MyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 149.56.96.31, server: localhost, request: "GET //MyAdmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 03:49:47 [error] 15360#0: *13 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.sbjudge1.com/azenv.php HTTP/1.1", host: "www.sbjudge1.com"
2016/08/05 06:21:58 [error] 15360#0: *30 open() "/opt/openresty/nginx/html/cache/global/img/gs.gif" failed (2: No such file or directory), client: 80.82.78.38, server: localhost, request: "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1", host: "www.baidu.com"
2016/08/05 08:11:43 [error] 15360#0: *40 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.proxy-listen.de/azenv.php HTTP/1.1", host: "www.proxy-listen.de"
2016/08/05 09:46:12 [error] 15360#0: *49 open() "/opt/openresty/nginx/html/muieblackcat" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET /muieblackcat HTTP/1.1", host: "119.29.33.243"
2016/08/05 09:46:12 [error] 15360#0: *50 open() "/opt/openresty/nginx/html/phpMyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //phpMyAdmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 09:46:13 [error] 15360#0: *51 open() "/opt/openresty/nginx/html/phpmyadmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //phpmyadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 09:46:13 [error] 15360#0: *52 open() "/opt/openresty/nginx/html/pma/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //pma/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 09:46:13 [error] 15360#0: *53 open() "/opt/openresty/nginx/html/myadmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //myadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 09:46:14 [error] 15360#0: *54 open() "/opt/openresty/nginx/html/MyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //MyAdmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 10:39:44 [error] 15360#0: *58 open() "/opt/openresty/nginx/html/phpmyadmin" failed (2: No such file or directory), client: 123.57.27.63, server: localhost, request: "GET /phpmyadmin HTTP/1.1", host: "119.29.33.243", referrer: "http://119.29.33.243/phpmyadmin"
2016/08/05 10:41:34 [error] 15360#0: *59 open() "/opt/openresty/nginx/html/testproxy.php" failed (2: No such file or directory), client: 185.25.148.240, server: localhost, request: "GET http://testp1.piwo.pila.pl/testproxy.php HTTP/1.1", host: "testp1.piwo.pila.pl"
2016/08/05 10:55:00 [error] 15360#0: *61 open() "/opt/openresty/nginx/html/robots.txt" failed (2: No such file or directory), client: 71.6.165.200, server: localhost, request: "GET /robots.txt HTTP/1.1", host: "119.29.33.243"
2016/08/05 10:55:00 [error] 15360#0: *62 open() "/opt/openresty/nginx/html/sitemap.xml" failed (2: No such file or directory), client: 71.6.165.200, server: localhost, request: "GET /sitemap.xml HTTP/1.1", host: "119.29.33.243"
2016/08/05 11:16:25 [error] 15360#0: *63 open() "/opt/openresty/nginx/html/muieblackcat" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET /muieblackcat HTTP/1.1", host: "119.29.33.243"
2016/08/05 11:16:25 [error] 15360#0: *64 open() "/opt/openresty/nginx/html/phpMyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //phpMyAdmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 11:16:26 [error] 15360#0: *65 open() "/opt/openresty/nginx/html/phpmyadmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //phpmyadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 11:16:26 [error] 15360#0: *66 open() "/opt/openresty/nginx/html/pma/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //pma/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 11:16:27 [error] 15360#0: *67 open() "/opt/openresty/nginx/html/myadmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //myadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 11:16:28 [error] 15360#0: *68 open() "/opt/openresty/nginx/html/MyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //MyAdmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 12:01:06 [error] 15360#0: *72 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.sbjudge2.com/azenv.php HTTP/1.1", host: "www.sbjudge2.com"
2016/08/05 12:32:32 [error] 15360#0: *77 open() "/opt/openresty/nginx/html/404" failed (2: No such file or directory), client: 61.216.2.13, server: localhost, request: "POST /404 HTTP/1.1", host: "8.8.8.8"
2016/08/05 14:03:56 [error] 15360#0: *82 open() "/opt/openresty/nginx/html/pma/scripts/setup.php" failed (2: No such file or directory), client: 101.226.64.174, server: localhost, request: "GET //pma/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 14:06:55 [error] 15360#0: *83 open() "/opt/openresty/nginx/html/pma/scripts/setup.php" failed (2: No such file or directory), client: 180.153.211.172, server: localhost, request: "GET //pma/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 14:11:36 [error] 15360#0: *86 open() "/opt/openresty/nginx/html/phpMyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 101.226.51.228, server: localhost, request: "GET //phpMyAdmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 14:18:24 [error] 15360#0: *87 open() "/opt/openresty/nginx/html/muieblackcat" failed (2: No such file or directory), client: 180.153.206.23, server: localhost, request: "GET /muieblackcat HTTP/1.1", host: "119.29.33.243"
2016/08/05 14:23:28 [error] 15360#0: *88 open() "/opt/openresty/nginx/html/muieblackcat" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET /muieblackcat HTTP/1.1", host: "119.29.33.243"
2016/08/05 14:23:28 [error] 15360#0: *89 open() "/opt/openresty/nginx/html/phpMyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //phpMyAdmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 14:23:29 [error] 15360#0: *90 open() "/opt/openresty/nginx/html/phpmyadmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //phpmyadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 14:23:30 [error] 15360#0: *91 open() "/opt/openresty/nginx/html/pma/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //pma/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 14:23:30 [error] 15360#0: *92 open() "/opt/openresty/nginx/html/myadmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //myadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 14:23:31 [error] 15360#0: *93 open() "/opt/openresty/nginx/html/MyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 198.167.140.108, server: localhost, request: "GET //MyAdmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 15:07:04 [error] 15360#0: *96 open() "/opt/openresty/nginx/html/av.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://domkrim.com/av.php HTTP/1.1", host: "domkrim.com"
2016/08/05 15:07:41 [error] 15360#0: *98 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.luisaranguren.com/azenv.php HTTP/1.1", host: "www.luisaranguren.com"
2016/08/05 16:27:23 [error] 15360#0: *104 open() "/opt/openresty/nginx/html/testproxy.php" failed (2: No such file or directory), client: 185.25.148.240, server: localhost, request: "GET http://testp1.piwo.pila.pl/testproxy.php HTTP/1.1", host: "testp1.piwo.pila.pl"
2016/08/05 17:08:42 [error] 15360#0: *107 open() "/opt/openresty/nginx/html/check_proxy.php" failed (2: No such file or directory), client: 182.254.154.72, server: localhost, request: "GET http://115.159.79.85/check_proxy.php HTTP/1.1", host: "115.159.79.85"
2016/08/05 17:38:16 [error] 15360#0: *108 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.proxy-listen.de/azenv.php HTTP/1.1", host: "www.proxy-listen.de"
2016/08/05 18:20:11 [error] 15360#0: *113 open() "/opt/openresty/nginx/html/phpmyadmin" failed (2: No such file or directory), client: 123.57.27.63, server: localhost, request: "GET /phpmyadmin HTTP/1.1", host: "119.29.33.243", referrer: "http://119.29.33.243/phpmyadmin"
2016/08/05 18:55:44 [error] 15360#0: *117 open() "/opt/openresty/nginx/html/phpmyadmin/scripts/setup.php" failed (2: No such file or directory), client: 101.226.33.216, server: localhost, request: "GET //phpmyadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 18:55:44 [error] 15360#0: *118 open() "/opt/openresty/nginx/html/phpmyadmin/scripts/setup.php" failed (2: No such file or directory), client: 101.226.33.225, server: localhost, request: "GET //phpmyadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 18:55:44 [error] 15360#0: *119 open() "/opt/openresty/nginx/html/phpmyadmin/scripts/setup.php" failed (2: No such file or directory), client: 101.226.65.104, server: localhost, request: "GET //phpmyadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 18:55:44 [error] 15360#0: *120 open() "/opt/openresty/nginx/html/phpmyadmin/scripts/setup.php" failed (2: No such file or directory), client: 61.151.218.119, server: localhost, request: "GET //phpmyadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 19:06:50 [error] 15360#0: *121 open() "/opt/openresty/nginx/html/phpmyadmin/scripts/setup.php" failed (2: No such file or directory), client: 180.153.214.188, server: localhost, request: "GET //phpmyadmin/scripts/setup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 19:28:11 [error] 15360#0: *124 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.proxy-listen.de/azenv.php HTTP/1.1", host: "www.proxy-listen.de"
2016/08/05 19:44:28 [error] 15360#0: *125 "/opt/openresty/nginx/html/stalker_portal/c/index.html" is not found (2: No such file or directory), client: 185.35.63.56, server: localhost, request: "GET /stalker_portal/c/ HTTP/1.1", host: "119.29.33.243:80"
2016/08/05 20:28:49 [error] 15360#0: *129 open() "/opt/openresty/nginx/html/check_proxy.php" failed (2: No such file or directory), client: 182.254.154.72, server: localhost, request: "GET http://115.159.79.85/check_proxy.php HTTP/1.1", host: "115.159.79.85"
2016/08/05 22:22:31 [error] 15360#0: *138 open() "/opt/openresty/nginx/html/av.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://domkrim.com/av.php HTTP/1.1", host: "domkrim.com"
2016/08/05 22:23:00 [error] 15360#0: *140 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.luisaranguren.com/azenv.php HTTP/1.1", host: "www.luisaranguren.com"
2016/08/05 22:30:52 [error] 15360#0: *144 open() "/opt/openresty/nginx/html/cache/global/img/gs.gif" failed (2: No such file or directory), client: 163.172.173.62, server: localhost, request: "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1", host: "www.baidu.com"
2016/08/05 23:17:37 [error] 15360#0: *148 open() "/opt/openresty/nginx/html/startup.php" failed (2: No such file or directory), client: 101.204.31.245, server: localhost, request: "GET /startup.php HTTP/1.1", host: "119.29.33.243"
2016/08/05 23:28:18 [error] 15360#0: *149 open() "/opt/openresty/nginx/html/manager/html" failed (2: No such file or directory), client: 101.201.53.64, server: localhost, request: "GET /manager/html HTTP/1.1", host: "119.29.33.243:80"
2016/08/06 01:22:23 [error] 15360#0: *155 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.proxyjudge.info/azenv.php HTTP/1.1", host: "www.proxyjudge.info"
2016/08/06 01:31:02 [error] 15360#0: *159 open() "/opt/openresty/nginx/html/phpmyadmin" failed (2: No such file or directory), client: 115.58.106.39, server: localhost, request: "GET /phpmyadmin HTTP/1.1", host: "119.29.33.243", referrer: "http://119.29.33.243/phpmyadmin"
2016/08/06 01:33:21 [error] 15360#0: *161 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.luisaranguren.com/azenv.php HTTP/1.1", host: "www.luisaranguren.com"
2016/08/06 01:44:21 [error] 15360#0: *163 open() "/opt/openresty/nginx/html/phpmyadmin" failed (2: No such file or directory), client: 101.226.64.174, server: localhost, request: "GET /phpmyadmin HTTP/1.1", host: "119.29.33.243"
2016/08/06 02:59:15 [error] 15360#0: *170 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.proxyjudge.info/azenv.php HTTP/1.1", host: "www.proxyjudge.info"
2016/08/06 04:25:19 [error] 15360#0: *178 open() "/opt/openresty/nginx/html/testproxy.php" failed (2: No such file or directory), client: 185.25.151.159, server: localhost, request: "GET http://testp1.piwo.pila.pl/testproxy.php HTTP/1.1", host: "testp1.piwo.pila.pl"
2016/08/06 04:37:20 [error] 15360#0: *179 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.proxy-listen.de/azenv.php HTTP/1.1", host: "www.proxy-listen.de"
2016/08/06 04:55:05 [error] 15360#0: *184 open() "/opt/openresty/nginx/html/cache/global/img/gs.gif" failed (2: No such file or directory), client: 80.82.78.38, server: localhost, request: "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1", host: "www.baidu.com"
2016/08/06 06:10:35 [error] 15360#0: *193 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.luisaranguren.com/azenv.php HTTP/1.1", host: "www.luisaranguren.com"
2016/08/06 07:21:28 [error] 15360#0: *201 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.proxyjudge.info/azenv.php HTTP/1.1", host: "www.proxyjudge.info"
2016/08/06 09:19:58 [error] 15360#0: *212 open() "/opt/openresty/nginx/html/check_proxy.php" failed (2: No such file or directory), client: 182.254.154.72, server: localhost, request: "GET http://115.159.79.85/check_proxy.php HTTP/1.1", host: "115.159.79.85"
2016/08/06 09:37:51 [error] 15360#0: *213 open() "/opt/openresty/nginx/html/manager/html" failed (2: No such file or directory), client: 101.226.65.105, server: localhost, request: "GET /manager/html HTTP/1.1", host: "119.29.33.243"
2016/08/06 09:45:03 [error] 15360#0: *216 open() "/opt/openresty/nginx/html/startup.php" failed (2: No such file or directory), client: 180.153.206.21, server: localhost, request: "GET /startup.php HTTP/1.1", host: "119.29.33.243"
2016/08/06 10:19:09 [error] 15360#0: *226 open() "/opt/openresty/nginx/html/nice ports,/Trinity.txt.bak" failed (2: No such file or directory), client: 113.105.95.188, server: localhost, request: "GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0"
2016/08/06 10:44:35 [error] 15360#0: *233 open() "/opt/openresty/nginx/html/azenv.php" failed (2: No such file or directory), client: 23.251.51.125, server: localhost, request: "GET http://www.sbjudge1.com/azenv.php HTTP/1.1", host: "www.sbjudge1.com"
2016/08/06 12:10:45 [error] 15360#0: *244 open() "/opt/openresty/nginx/html/manager/html" failed (2: No such file or directory), client: 60.173.61.17, server: localhost, request: "GET /manager/html HTTP/1.1", host: "119.29.33.243:80"
2016/08/06 12:40:28 [error] 15360#0: *245 open() "/opt/openresty/nginx/html/manager/html" failed (2: No such file or directory), client: 60.173.61.17, server: localhost, request: "GET /manager/html HTTP/1.1", host: "119.29.33.243:80"
2016/08/10 11:39:04 [alert] 13162#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/nginx.conf:39
2016/08/10 11:39:04 [notice] 13162#0: signal process started
2016/08/10 11:39:04 [alert] 9361#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/nginx.conf:39
2016/08/10 11:39:31 [alert] 13166#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/nginx.conf:39
2016/10/04 22:46:28 [alert] 24342#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/04 22:46:28 [notice] 24342#0: signal process started
2016/10/04 22:46:28 [alert] 24342#0: kill(13167, 1) failed (3: No such process)
2016/10/04 22:48:07 [alert] 24459#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/04 22:48:12 [alert] 24463#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/04 22:48:12 [emerg] 24463#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/10/04 22:48:12 [emerg] 24463#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/10/04 22:48:12 [emerg] 24463#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/10/04 22:48:12 [emerg] 24463#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/10/04 22:48:12 [emerg] 24463#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/10/04 22:48:12 [emerg] 24463#0: still could not bind()
2016/10/04 22:48:28 [alert] 24467#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/04 22:48:28 [notice] 24467#0: signal process started
2016/10/04 22:48:28 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/04 22:55:57 [emerg] 24783#0: getpwnam("spotless") failed in /opt/openresty/nginx/conf/nginx.conf:2
2016/10/04 22:56:49 [alert] 24827#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/04 22:56:49 [emerg] 24827#0: unknown directive "accless_log" in /opt/openresty/nginx/conf/ngx_private_cloud.conf:9
2016/10/04 22:57:10 [alert] 24870#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/04 22:57:10 [emerg] 24870#0: unexpected "}" in /opt/openresty/nginx/conf/ngx_private_cloud.conf:20
2016/10/04 22:57:54 [alert] 24873#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/04 22:57:54 [notice] 24873#0: signal process started
2016/10/04 22:57:54 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/04 22:58:03 [alert] 24908#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/04 22:58:03 [notice] 24908#0: signal process started
2016/10/04 22:58:03 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/06 23:59:12 [alert] 22453#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/06 23:59:12 [emerg] 22453#0: unexpected "}" in /opt/openresty/nginx/conf/ngx_private_cloud.conf:34
2016/10/06 23:59:30 [alert] 22455#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/06 23:59:30 [notice] 22455#0: signal process started
2016/10/06 23:59:30 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/07 00:00:27 [error] 22456#0: *438 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:02:26 [error] 22456#0: *439 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:03:11 [error] 22456#0: *440 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 223.74.51.22, server: skycloud, request: "GET /api/uploadData.json HTTP/1.1", host: "119.29.33.243"
2016/10/07 00:03:49 [error] 22456#0: *441 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 223.74.51.22, server: skycloud, request: "GET /api/uploadData.json?mid=0&&did=nil HTTP/1.1", host: "119.29.33.243"
2016/10/07 00:03:52 [error] 22456#0: *442 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 223.74.51.22, server: skycloud, request: "GET /api/uploadData.json?mid=0&&did=nil HTTP/1.1", host: "119.29.33.243"
2016/10/07 00:04:00 [error] 22456#0: *444 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 223.74.51.22, server: skycloud, request: "GET /api/uploadData.json?mid=0&&did=0 HTTP/1.1", host: "119.29.33.243"
2016/10/07 00:04:17 [error] 22456#0: *446 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 223.74.51.22, server: skycloud, request: "GET /api/uploadData.json?mid=0&&did=0 HTTP/1.1", host: "119.29.33.243"
2016/10/07 00:04:21 [error] 22456#0: *447 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 223.74.51.22, server: skycloud, request: "GET /api/uploadData.json?mid=0&&did=0 HTTP/1.1", host: "119.29.33.243"
2016/10/07 00:04:22 [error] 22456#0: *448 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 223.74.51.22, server: skycloud, request: "GET /api/uploadData.json?mid=0&&did=0 HTTP/1.1", host: "119.29.33.243"
2016/10/07 00:04:27 [error] 22456#0: *449 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 223.74.51.22, server: skycloud, request: "GET /api/uploadData.json HTTP/1.1", host: "119.29.33.243"
2016/10/07 00:04:44 [error] 22456#0: *450 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 223.74.51.22, server: skycloud, request: "GET /api/uploadData.json?mid%20=%20nil HTTP/1.1", host: "119.29.33.243"
2016/10/07 00:04:49 [error] 22456#0: *452 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 223.74.51.22, server: skycloud, request: "GET /api/uploadData.json?mid%20=%20nil HTTP/1.1", host: "119.29.33.243"
2016/10/07 00:06:30 [error] 22456#0: *455 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:06:55 [error] 22456#0: *456 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:07:04 [error] 22456#0: *457 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:07:52 [error] 22456#0: *458 failed to load external Lua file "/opt/openresty/nginx/lua/api/uploadData.lua": /opt/openresty/nginx/lua/api/uploadData.lua:4: 'then' expected near 'andargs', client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:08:00 [error] 22456#0: *459 failed to load external Lua file "/opt/openresty/nginx/lua/api/uploadData.lua": /opt/openresty/nginx/lua/api/uploadData.lua:4: 'then' expected near 'andargs', client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:08:38 [error] 22456#0: *460 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:3: attempt to call field 'get_url_args' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:11:13 [warn] 22456#0: *467 [lua] uploadData.lua:5: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:11:31 [warn] 22456#0: *468 [lua] uploadData.lua:5: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:11:35 [warn] 22456#0: *469 [lua] uploadData.lua:5: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?did=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:11:42 [warn] 22456#0: *470 [lua] uploadData.lua:5: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?did=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:12:06 [warn] 22456#0: *471 [lua] uploadData.lua:5: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?did=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:12:55 [warn] 22456#0: *472 [lua] uploadData.lua:5: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?did=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:13:16 [warn] 22456#0: *473 [lua] uploadData.lua:5: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?did=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:13:35 [warn] 22456#0: *474 [lua] uploadData.lua:5: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:16:00 [warn] 22456#0: *475 [lua] uploadData.lua:5: request args uid is nil or did is nil, client: 223.74.51.22, server: skycloud, request: "GET /api/uploadData.json HTTP/1.1", host: "119.29.33.243"
2016/10/07 00:17:52 [warn] 22456#0: *478 [lua] uploadData.lua:10: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:18:17 [warn] 22456#0: *479 [lua] uploadData.lua:10: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:18:17 [error] 22456#0: *479 attempt to set status 400 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:22:00 [warn] 22456#0: *487 [lua] uploadData.lua:7: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:22:04 [warn] 22456#0: *488 [lua] uploadData.lua:7: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:22:07 [warn] 22456#0: *489 [lua] uploadData.lua:7: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid= HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:22:10 [warn] 22456#0: *490 [lua] uploadData.lua:7: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:30:37 [warn] 22456#0: *495 [lua] uploadData.lua:7: request args uid is nil or did is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:34:05 [alert] 24031#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/07 00:34:05 [notice] 24031#0: signal process started
2016/10/07 00:34:05 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/07 00:35:19 [warn] 24032#0: *503 [lua] uploadData.lua:15: bad request args uid P:nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=44&did=3 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:36:31 [warn] 24032#0: *506 [lua] uploadData.lua:19: right request args uid :4, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=4 HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:36:43 [warn] 24032#0: *507 [lua] uploadData.lua:19: right request args uid :, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid= HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:37:03 [warn] 24032#0: *508 [lua] uploadData.lua:19: right request args uid :true, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid HTTP/1.1", host: "127.0.0.1"
2016/10/07 00:42:17 [warn] 24032#0: *509 [lua] uploadData.lua:19: right request args uid :, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid= HTTP/1.1", host: "127.0.0.1"
2016/10/07 10:46:02 [warn] 24032#0: *582 [lua] uploadData.lua:15: bad request args uid :nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json HTTP/1.1", host: "127.0.0.1"
2016/10/07 10:46:50 [warn] 24032#0: *583 [lua] uploadData.lua:15: bad request args uid :nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json HTTP/1.1", host: "127.0.0.1"
2016/10/07 10:47:13 [warn] 24032#0: *584 [lua] uploadData.lua:19: right request args uid :, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid= HTTP/1.1", host: "127.0.0.1"
2016/10/07 10:48:19 [warn] 24032#0: *585 [lua] uploadData.lua:15: bad request args uid,did:nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid= HTTP/1.1", host: "127.0.0.1"
2016/10/07 10:48:31 [warn] 24032#0: *586 [lua] uploadData.lua:15: bad request args uid,did:2nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 10:49:07 [warn] 24032#0: *587 [lua] uploadData.lua:19: right request args uid :2, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=2&did HTTP/1.1", host: "127.0.0.1"
2016/10/07 10:49:13 [warn] 24032#0: *588 [lua] uploadData.lua:19: right request args uid :2, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=2&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 11:06:17 [warn] 24032#0: *589 [lua] uploadData.lua:21: right request args uid :2, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=2&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 11:06:28 [warn] 24032#0: *590 [lua] uploadData.lua:21: right request args uid :2, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=2&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 11:10:39 [warn] 24032#0: *591 [lua] uploadData.lua:21: right request args uid :2, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=2&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 21:08:01 [error] 24032#0: *660 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:1: module 'comm.common' not found:
	no field package.preload['comm.common']
	no file '/opt/openresty/nginx//comm/common.lua'
	no file '/opt/openresty/nginx/comm/common.lua'
	no file '/opt/openresty/lualib/comm/common.lua'
	no file '/opt/openresty/lualib/comm/common/init.lua'
	no file './comm/common.lua'
	no file '/opt/openresty/luajit/share/luajit-2.1.0-beta2/comm/common.lua'
	no file '/usr/local/share/lua/5.1/comm/common.lua'
	no file '/usr/local/share/lua/5.1/comm/common/init.lua'
	no file '/opt/openresty/luajit/share/lua/5.1/comm/common.lua'
	no file '/opt/openresty/luajit/share/lua/5.1/comm/common/init.lua'
	no file '/opt/openresty/lualib/comm/common.so'
	no file './comm/common.so'
	no file '/usr/local/lib/lua/5.1/comm/common.so'
	no file '/opt/openresty/luajit/lib/lua/5.1/comm/common.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/opt/openresty/lualib/comm.so'
	no file './comm.so'
	no file '/usr/local/lib/lua/5.1/comm.so'
	no file '/opt/openresty/luajit/lib/lua/5.1/comm.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/opt/openresty/nginx/lua/api/uploadData.lua:1: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 21:10:38 [alert] 13110#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/07 21:10:38 [notice] 13110#0: signal process started
2016/10/07 21:10:38 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/07 21:10:48 [error] 13111#0: *661 lua entry thread aborted: runtime error: error loading module 'comm.common' from file '/opt/openresty/nginx/lua/comm/common.lua':
	/opt/openresty/nginx/lua/comm/common.lua:50: '<eof>' expected near 'end'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/opt/openresty/nginx/lua/api/uploadData.lua:1: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 21:17:08 [error] 13111#0: *663 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:19: attempt to index local 'commom' (a boolean value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 21:20:23 [error] 13111#0: *664 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:19: attempt to index local 'comm' (a boolean value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 21:29:30 [warn] 13111#0: *665 [lua] uploadData.lua:19: request body is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 21:31:11 [warn] 13111#0: *666 [lua] uploadData.lua:19: request body is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploadData.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 21:31:24 [warn] 13111#0: *667 [lua] uploaddata.lua:19: request body is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploaddata.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 22:09:52 [warn] 13111#0: *670 [lua] uploaddata.lua:19: request body is nil, client: 127.0.0.1, server: skycloud, request: "GET /api/uploaddata.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 22:10:07 [error] 13111#0: *671 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploaddata.lua:23: attempt to index local 'comm' (a boolean value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploaddata.lua: in function </opt/openresty/nginx/lua/api/uploaddata.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploaddata.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 22:14:10 [error] 13111#0: *672 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploaddata.lua:24: attempt to call field 'json_decode' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploaddata.lua: in function </opt/openresty/nginx/lua/api/uploaddata.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploaddata.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 22:15:51 [warn] 13111#0: *673 [lua] uploaddata.lua:26: error request body,probably is not a table, client: 127.0.0.1, server: skycloud, request: "POST /api/uploaddata.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 22:16:15 [warn] 13111#0: *674 [lua] uploaddata.lua:26: error request body,probably is not a table, client: 127.0.0.1, server: skycloud, request: "POST /api/uploaddata.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 22:17:42 [warn] 13111#0: *675 [lua] uploaddata.lua:26: error request body,probably is not a table, client: 127.0.0.1, server: skycloud, request: "POST /api/uploaddata.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 23:03:54 [warn] 13111#0: *680 [lua] uploaddata.lua:26: error request body,probably is not a table, client: 127.0.0.1, server: skycloud, request: "POST /api/uploaddata.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/07 23:04:07 [warn] 13111#0: *681 [lua] uploaddata.lua:30: right request args uid :1, client: 127.0.0.1, server: skycloud, request: "POST /api/uploaddata.json?uid=1&did=2 HTTP/1.1", host: "127.0.0.1"
2016/10/08 00:32:54 [alert] 21884#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/08 00:32:54 [notice] 21884#0: signal process started
2016/10/08 00:32:54 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/11 17:44:52 [error] 21885#0: *2168 lua entry thread aborted: runtime error: /opt/openresty/nginx//lua/db_redis/db_base.lua:225: bad argument #2 to 'set_keepalive_mod' (number expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'set_keepalive_mod'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:225: in function 'hget'
	/opt/openresty/nginx/lua/api/uploadData.lua:57: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 17:48:32 [error] 21885#0: *2170 lua entry thread aborted: runtime error: /opt/openresty/nginx//lua/db_redis/db_base.lua:225: bad argument #2 to 'set_keepalive_mod' (number expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'set_keepalive_mod'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:225: in function 'hget'
	/opt/openresty/nginx/lua/api/uploadData.lua:57: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 17:51:38 [warn] 21885#0: *2172 [lua] uploadData.lua:71: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:05:15 [warn] 21885#0: *2179 [lua] uploadData.lua:75: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:06:29 [warn] 21885#0: *2181 [lua] uploadData.lua:75: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:08:43 [warn] 21885#0: *2183 [lua] uploadData.lua:79: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:09:10 [warn] 21885#0: *2185 [lua] uploadData.lua:79: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:09:45 [warn] 21885#0: *2187 [lua] uploadData.lua:79: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:18:12 [warn] 21885#0: *2189 [lua] uploadData.lua:79: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:18:46 [warn] 21885#0: *2191 [lua] uploadData.lua:79: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:19:21 [warn] 21885#0: *2193 [lua] uploadData.lua:79: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:19:49 [warn] 21885#0: *2195 [lua] uploadData.lua:78: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:27:02 [warn] 21885#0: *2197 [lua] uploadData.lua:80: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:33:54 [warn] 21885#0: *2201 [lua] uploadData.lua:74: k:1, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:33:54 [warn] 21885#0: *2201 [lua] uploadData.lua:74: k:2, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:33:54 [warn] 21885#0: *2201 [lua] uploadData.lua:76: length:2, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:33:54 [warn] 21885#0: *2201 [lua] uploadData.lua:81: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:42:37 [warn] 21885#0: *2203 [lua] uploadData.lua:74: k:1, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:42:37 [warn] 21885#0: *2203 [lua] uploadData.lua:74: k:2, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:42:37 [error] 21885#0: *2203 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:80: bad argument #1 to 'insert' (table expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'insert'
	/opt/openresty/nginx/lua/api/uploadData.lua:80: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:42:57 [warn] 21885#0: *2205 [lua] uploadData.lua:74: k:1, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:42:57 [warn] 21885#0: *2205 [lua] uploadData.lua:74: k:2, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:42:57 [warn] 21885#0: *2205 [lua] uploadData.lua:83: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:44:58 [warn] 21885#0: *2207 [lua] uploadData.lua:74: k:1, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:44:58 [warn] 21885#0: *2207 [lua] uploadData.lua:74: k:2, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:44:58 [warn] 21885#0: *2207 [lua] uploadData.lua:85: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:45:57 [warn] 21885#0: *2209 [lua] uploadData.lua:81: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:50:23 [warn] 21885#0: *2212 [lua] uploadData.lua:88: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:52:29 [error] 21885#0: *2214 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:75: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=002 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:53:03 [error] 21885#0: *2216 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:75: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=002 HTTP/1.1", host: "127.0.0.1"
2016/10/11 18:53:05 [error] 21885#0: *2218 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:75: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=002 HTTP/1.1", host: "127.0.0.1"
2016/10/11 19:10:50 [warn] 21885#0: *2224 [lua] uploadData.lua:88: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 13:41:02 [alert] 32545#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 13:41:02 [notice] 32545#0: signal process started
2016/10/13 13:41:02 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 14:03:10 [error] 32546#0: *2537 failed to load external Lua file "/opt/openresty/nginx/test_base_lua/unit/test_mock.lua": /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:38: 'end' expected (to close 'function' at line 1) near '<eof>', client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", host: "127.0.0.1"
2016/10/13 14:05:30 [error] 32546#0: *2539 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:1: module 'test_case_lua.test_base' not found:
	no field package.preload['test_case_lua.test_base']
	no file '/opt/openresty/nginx//test_case_lua/test_base.lua'
	no file '/opt/openresty/nginx/test_case_lua/test_base.lua'
	no file '/opt/openresty/nginx/lua/test_case_lua/test_base.lua'
	no file '/opt/openresty/lualib/test_case_lua/test_base.lua'
	no file '/opt/openresty/lualib/test_case_lua/test_base/init.lua'
	no file './test_case_lua/test_base.lua'
	no file '/opt/openresty/luajit/share/luajit-2.1.0-beta2/test_case_lua/test_base.lua'
	no file '/usr/local/share/lua/5.1/test_case_lua/test_base.lua'
	no file '/usr/local/share/lua/5.1/test_case_lua/test_base/init.lua'
	no file '/opt/openresty/luajit/share/lua/5.1/test_case_lua/test_base.lua'
	no file '/opt/openresty/luajit/share/lua/5.1/test_case_lua/test_base/init.lua'
	no file '/opt/openresty/lualib/test_case_lua/test_base.so'
	no file './test_case_lua/test_base.so'
	no file '/usr/local/lib/lua/5.1/test_case_lua/test_base.so'
	no file '/opt/openresty/luajit/lib/lua/5.1/test_case_lua/test_base.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/opt/openresty/lualib/test_case_lua.so'
	no file './test_case_lua.so'
	no file '/usr/local/lib/lua/5.1/test_case_lua.so'
	no file '/opt/openresty/luajit/lib/lua/5.1/test_case_lua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua:1: in function </opt/openresty/nginx/test_base_lua/unit/test_mock.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", host: "127.0.0.1"
2016/10/13 14:13:15 [alert] 32546#0: *2544 1024 worker_connections are not enough, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:13:15 [error] 32546#0: *2544 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/test.lua:15: hget error 2
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/opt/openresty/nginx/lua/test.lua:15: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:15:30 [alert] 32546#0: *3566 1024 worker_connections are not enough, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:15:30 [error] 32546#0: *3566 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/test.lua:15: hget error 2
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/opt/openresty/nginx/lua/test.lua:15: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:15:42 [alert] 1503#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 14:15:42 [notice] 1503#0: signal process started
2016/10/13 14:15:42 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 14:15:49 [alert] 1504#0: *4588 1024 worker_connections are not enough, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:15:49 [error] 1504#0: *4588 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/test.lua:15: hget error 2
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/opt/openresty/nginx/lua/test.lua:15: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:16:28 [alert] 1504#0: *5610 1024 worker_connections are not enough, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:18:16 [alert] 1504#0: *6632 1024 worker_connections are not enough, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:18:52 [alert] 1504#0: *7654 1024 worker_connections are not enough, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:20:09 [alert] 1504#0: *8678 1024 worker_connections are not enough, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:20:56 [alert] 1504#0: *9700 1024 worker_connections are not enough, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:21:25 [alert] 1504#0: *10722 1024 worker_connections are not enough, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:21:25 [error] 1504#0: *10722 attempt to set status 503 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:22:57 [error] 1504#0: *11744 failed to load external Lua file "/opt/openresty/nginx/test_base_lua/unit/test_mock.lua": /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:30: '=' expected near '+', client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", host: "127.0.0.1"
2016/10/13 14:24:36 [alert] 1504#0: *11745 1024 worker_connections are not enough, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:33:44 [error] 1504#0: *12773 lua entry thread aborted: runtime error: /opt/openresty/nginx//lua/db_redis/db_base.lua:215: attempt to call local 'fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx//lua/db_redis/db_base.lua: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:6: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:43:48 [error] 1504#0: *12776 lua entry thread aborted: runtime error: /opt/openresty/nginx//lua/db_redis/db_base.lua:215: attempt to call local 'fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx//lua/db_redis/db_base.lua: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:6: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:43:53 [error] 1504#0: *12778 lua entry thread aborted: runtime error: /opt/openresty/nginx//lua/db_redis/db_base.lua:215: attempt to call local 'fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx//lua/db_redis/db_base.lua: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:6: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 14:43:54 [error] 1504#0: *12780 lua entry thread aborted: runtime error: /opt/openresty/nginx//lua/db_redis/db_base.lua:215: attempt to call local 'fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx//lua/db_redis/db_base.lua: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:6: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:10:48 [error] 1504#0: *12802 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:11:38 [error] 1504#0: *12804 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:11:38 [error] 1504#0: *12806 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:11:39 [error] 1504#0: *12808 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:11:52 [error] 1504#0: *12810 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:12:05 [error] 1504#0: *12812 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:13:20 [error] 1504#0: *12814 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mmmm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:14:08 [error] 1504#0: *12816 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:14:10 [error] 1504#0: *12818 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:14:11 [error] 1504#0: *12820 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:17:04 [error] 1504#0: *12827 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:17:05 [error] 1504#0: *12829 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:17:06 [error] 1504#0: *12831 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:19:35 [error] 1504#0: *12833 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:20:07 [error] 1504#0: *12835 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:34:22 [error] 1504#0: *12840 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:35:00 [error] 1504#0: *12842 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:35:05 [error] 1504#0: *12844 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:35:05 [error] 1504#0: *12846 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:35:06 [error] 1504#0: *12848 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 15:35:07 [error] 1504#0: *12850 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:01:35 [error] 1504#0: *12853 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:01:44 [error] 1504#0: *12855 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:01:45 [error] 1504#0: *12857 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:01:45 [error] 1504#0: *12859 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:02:10 [error] 1504#0: *12861 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:03:14 [error] 1504#0: *12863 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:03:16 [error] 1504#0: *12865 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:03:17 [error] 1504#0: *12867 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:03:18 [error] 1504#0: *12869 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:16: attempt to index field 'mm' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:14:22 [error] 1504#0: *12874 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:14:30 [error] 1504#0: *12876 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:14:31 [error] 1504#0: *12878 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:15:52 [error] 1504#0: *12880 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:16:44 [error] 1504#0: *12882 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:17:06 [error] 1504#0: *12884 failed to load external Lua file "/opt/openresty/nginx/test_base_lua/unit/test_mock.lua": /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:34: ')' expected (to close '(' at line 33) near 'if', client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:17:34 [error] 1504#0: *12886 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:18:25 [error] 1504#0: *12888 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:19:01 [error] 1504#0: *12890 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:19:31 [error] 1504#0: *12892 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:19:59 [error] 1504#0: *12894 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:20:25 [error] 1504#0: *12896 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:21:19 [error] 1504#0: *12898 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:21:51 [error] 1504#0: *12900 lua entry thread aborted: runtime error: /opt/openresty/nginx/test_base_lua/unit/test_mock.lua:17: attempt to call local 'org_fun' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/test_base_lua/unit/test_mock.lua: in function 'fun'
	/opt/openresty/nginx//lua/db_redis/db_base.lua:215: in function 'hget'
	/opt/openresty/nginx/lua/test.lua:13: in function </opt/openresty/nginx/lua/test.lua:1>, client: 127.0.0.1, server: skycloud, request: "GET /test_unit/test_mock.json HTTP/1.1", subrequest: "/test", host: "127.0.0.1"
2016/10/13 16:27:22 [warn] 1504#0: *12902 [lua] uploadData.lua:88: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:27:28 [warn] 1504#0: *12904 [lua] uploadData.lua:88: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:27:29 [warn] 1504#0: *12906 [lua] uploadData.lua:88: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:27:53 [error] 1504#0: *12908 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:75: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=002 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:28:13 [error] 1504#0: *12910 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:75: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:28:29 [error] 1504#0: *12912 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:75: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:42 [warn] 1504#0: *12914 [lua] uploadData.lua:59: redis hget:, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:42 [error] 1504#0: *12914 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:76: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:47 [warn] 1504#0: *12916 [lua] uploadData.lua:59: redis hget:, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:47 [error] 1504#0: *12916 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:76: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:47 [warn] 1504#0: *12918 [lua] uploadData.lua:59: redis hget:, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:47 [error] 1504#0: *12918 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:76: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:48 [warn] 1504#0: *12920 [lua] uploadData.lua:59: redis hget:, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:48 [error] 1504#0: *12920 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:76: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:49 [warn] 1504#0: *12922 [lua] uploadData.lua:59: redis hget:, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:49 [error] 1504#0: *12922 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:76: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:49 [warn] 1504#0: *12924 [lua] uploadData.lua:59: redis hget:, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:29:50 [error] 1504#0: *12924 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:76: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:30:55 [warn] 1504#0: *12926 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:30:55 [error] 1504#0: *12926 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:77: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:32:09 [warn] 1504#0: *12928 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:32:09 [error] 1504#0: *12928 attempt to set status 400 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:32:24 [warn] 1504#0: *12930 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:32:24 [error] 1504#0: *12930 attempt to set status 400 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:34:20 [warn] 1504#0: *12932 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:34:20 [error] 1504#0: *12932 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:80: attempt to index local 'data' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:34:39 [warn] 1504#0: *12934 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:34:44 [warn] 1504#0: *12936 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:34:45 [warn] 1504#0: *12938 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:34:45 [warn] 1504#0: *12940 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:34:46 [warn] 1504#0: *12942 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:34:47 [warn] 1504#0: *12944 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:35:32 [warn] 1504#0: *12946 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:35:43 [warn] 1504#0: *12948 [lua] uploadData.lua:66: redis hget:{"createTime":"2016\/912","Sensor":[{"unit":"kg","name":"weight","createTime":"2013\/2\/3","designation":"体重"},{"unit":"次\/分","name":"heart","createTime":"2013\/2\/3","designation":"心率"}],"deviceName":"smartdev","data":[{"timestamp":"2016\/2\/3","sensor":"weight","value":78},{"timestamp":"2016\/4\/3","sensor":"heart","value":78},{"timestamp":"2016-10-11 18:50:23","sensor":"weight","value":78},{"timestamp":"2016-10-11 18:50:23","sensor":"heart","value":78},{"timestamp":"2016-10-11 19:10:50","sensor":"weight","value":78},{"timestamp":"2016-10-11 19:10:50","sensor":"heart","value":78},{"timestamp":"2016-10-13 16:27:22","sensor":"weight","value":78},{"timestamp":"2016-10-13 16:27:22","sensor":"heart","value":78},{"timestamp":"2016-10-13 16:27:28","sensor":"weight","value":78},{"timestamp":"2016-10-13 16:27:28","sensor":"heart","value":78},{"timestamp":"2016-10-13 16:27:29","sensor":"weight","value":78},{"timestamp":"2016-10-13 16:27:29","sensor":"heart","value":78}],"description":"none"}, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:35:43 [warn] 1504#0: *12948 [lua] uploadData.lua:91: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:35:58 [warn] 1504#0: *12950 [lua] uploadData.lua:66: redis hget:nil, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=002&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:45:53 [warn] 1504#0: *12954 [lua] uploadData.lua:66: redis hget:{"data":[{"timestamp":"2016\/2\/3","sensor":"weight","value":78},{"timestamp":"2016\/4\/3","sensor":"heart","value":78},{"timestamp":"2016-10-11 18:50:23","sensor":"weight","value":78},{"timestamp":"2016-10-11 18:50:23","sensor":"heart","value":78},{"timestamp":"2016-10-11 19:10:50","sensor":"weight","value":78},{"timestamp":"2016-10-11 19:10:50","sensor":"heart","value":78},{"timestamp":"2016-10-13 16:27:22","sensor":"weight","value":78},{"timestamp":"2016-10-13 16:27:22","sensor":"heart","value":78},{"timestamp":"2016-10-13 16:27:28","sensor":"weight","value":78},{"timestamp":"2016-10-13 16:27:28","sensor":"heart","value":78},{"timestamp":"2016-10-13 16:27:29","sensor":"weight","value":78},{"timestamp":"2016-10-13 16:27:29","sensor":"heart","value":78},{"timestamp":"2016-10-13 16:35:43","sensor":"weight","value":78},{"timestamp":"2016-10-13 16:35:43","sensor":"heart","value":78}],"createTime":"2016\/912","deviceName":"smartdev","Sensor":[{"name":"weight","createTime":"2013\/2\/3","unit":"kg","designation":"体重"},{"name":"heart","createTime":"2013\/2\/3","unit":"次\/分","designation":"心率"}],"description":"none"}, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 16:45:53 [warn] 1504#0: *12954 [lua] uploadData.lua:91: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 17:18:51 [error] 1504#0: *12958 lua entry thread aborted: runtime error: /opt/openresty/nginx/lua/api/uploadData.lua:74: attempt to call global 'check_data_sersor' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx/lua/api/uploadData.lua: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 17:19:11 [error] 1504#0: *12960 lua entry thread aborted: runtime error: /opt/openresty/nginx//lua/db_redis/db.lua:15: attempt to index global 'db_sersor' (a nil value)
stack traceback:
coroutine 0:
	/opt/openresty/nginx//lua/db_redis/db.lua: in function 'check_data_sersor'
	/opt/openresty/nginx/lua/api/uploadData.lua:74: in function </opt/openresty/nginx/lua/api/uploadData.lua:1>, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 17:20:19 [warn] 1504#0: *12964 [lua] uploadData.lua:94: right request args uid :001, client: 127.0.0.1, server: skycloud, request: "POST /api/uploadData.json?uid=001&did=001 HTTP/1.1", host: "127.0.0.1"
2016/10/13 18:33:16 [alert] 12881#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 18:33:16 [emerg] 12881#0: unknown "prefix" variable
2016/10/13 18:34:01 [alert] 12883#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 18:34:01 [notice] 12883#0: signal process started
2016/10/13 18:34:01 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 18:34:08 [alert] 12929#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 18:34:08 [notice] 12929#0: signal process started
2016/10/13 18:34:08 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 18:35:06 [alert] 12979#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 18:35:06 [notice] 12979#0: signal process started
2016/10/13 18:35:06 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 18:37:07 [warn] 12980#0: *12983 [lua] html.lua:4: html...., client: 127.0.0.1, server: skycloud, request: "GET /html HTTP/1.1", host: "127.0.0.1"
2016/10/13 18:37:43 [alert] 13070#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 18:37:43 [notice] 13070#0: signal process started
2016/10/13 18:37:43 [alert] 24460#0: lua_code_cache is off; this will hurt performance in /opt/openresty/nginx/conf/ngx_private_cloud.conf:3
2016/10/13 18:37:50 [warn] 13071#0: *12984 [lua] html.lua:4: html...., client: 127.0.0.1, server: skycloud, request: "GET /html HTTP/1.1", host: "127.0.0.1"
2016/10/13 18:38:26 [warn] 13071#0: *12985 [lua] html.lua:4: html...., client: 127.0.0.1, server: skycloud, request: "GET /html HTTP/1.1", host: "127.0.0.1"
2016/10/13 18:38:28 [warn] 13071#0: *12986 [lua] html.lua:4: html...., client: 127.0.0.1, server: skycloud, request: "GET /html HTTP/1.1", host: "127.0.0.1"
